version: '3'

services:
  nginx_fullcycle:
    image: nginx:latest
    container_name: nginx_fullcycle
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_fullcycle
    networks: 
      - fullcycle

  app_fullcycle:
    build: ./app
    container_name: app_fullcycle
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    entrypoint: dockerize --wait tcp://mysql_fullcycle:3306 --timeout 60s docker-entrypoint.sh node index.js
    depends_on:
      - mysql_fullcycle
    environment:
      NODE_ENV: development
    networks:
      - fullcycle

  mysql_fullcycle:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    container_name: mysql_fullcycle 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - fullcycle

volumes:
  mysql:
    driver: local

networks:
  fullcycle:
    driver: bridge
